version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      # - ls /etc/apt/sources.list.d/
      # - rm --force /etc/apt/sources.list.d/*
      # - add-apt-repository universe
      # - add-apt-repository multiverse
      # - apt-get update
      # - apt-get install -y python3-venv
      # - python3.6 -m venv test_venv
      # - . test_venv/bin/activate
      # - pip install --upgrade pip
      # - pip install .
      # - pip install -r tests/requirements.txt
      # - rm -rf dspt
      # - mkdir test-reports
      - apt-get update
      - apt-get install nginx -y
      - service nginx start

  build:
    commands:
      # - pytest 
      #   --html=test-reports/report.html 
      #   --self-contained-html
      #   -s
      #   -v
      #   --cov=dspt 
      #   --cov-report=html:test-reports/coverage 
      #   --junitxml=test-reports/junit.xml 
      #   --log-file=test-reports/logs.txt 
      #   tests
      - npm install
      - npm run build
      - npm run start &
      - cp proxy/joeygonz.com /etc/nginx/sites-available
      - ln -s /etc/nginx/sites-available/joeygonz.com /etc/nginx/sites-enabled
      - service nginx restart

  post_build:
    commands:
      - echo Build completed on `date`
      - curl localhost:3000
      - printf '[{"name":"your.task.definition.name","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

# reports:
#   coverage:
#     files:
#       - "coverage/*"
#     base-directory: 'test-reports'
#     discard-paths: yes
#   report:
#     files:
#       - 'junit.xml'
#       - 'report.html'
#       - 'assets/*'
#     base-directory: 'test-reports'
#     discard-paths: yes
#     file-format: JunitXml
